# Chapter 11
# Dates And Times

#------------------ Date and Time Classes

# There are three date and time classes that come with R: POSIXct, POSIXlt, and Date.

#------------------ POSIX Dates and Times

# The two standard date-time classes in R are POSIXct and POSIXlt.
# ct is short for calendar time
# POSIXct class stores dates as the number of seconds since the start of 1970
# POSIXlt stores dates as a list, with components for seconds, minutes, hours, day of month, etc

# POSIXct is best for storing dates and calculating with them
# POSIXlt is best for extracting specific parts of a date.

# The function Sys.time returns the current date and time in POSIXct form:
(now_ct <- Sys.time())


# The class of now_ct has two elements. 
# [1] It is a POSIXct variable
# [2] POSIXct is inherited from the class POSIXt
class(now_ct)

# When a date is printed, we see a formatted version of it
# By using unclass, we can see that it is indeed just a number
unclass(now_ct)


# The POSIXlt date looks exactly the same as POSIXct, but underneath the storage mechanism is very different
(now_lt <- as.POSIXlt(now_ct))
class(now_lt)
unclass(now_lt)

# You can use list indexing to access individual components of a POSIXlt date:
now_lt$sec
# now_lt[["min"]]      # Not Working


#---------------------- The Date Class

# It is 3rd date class in R: Date Class
# This stores dates as the number of days since the start of 1970.
# The Date class is best used when you don’t care about the time of day
# Fractional days are possible (and can be generated by calculating a mean Date) 
# But the POSIX classes are better for those situations

(now_date <- as.Date(now_ct))
class(now_date)
unclass(now_date)



#----------------------- Other Date Classes

# There are lots of other date and time classes scattered through other R classes
# Other date and time classes from add-on packages include date, dates, chron, yearmon, yearqtr, timeDate, ti, and jul.



#----------------------- Conversion to and from Strings
# Many text file formats for data don’t explicitly support specific date types.
# CSV to Variable to CSV

# Parsing Dates
# Reading dates from a text or spreadsheet file, they will typically be stored as a character vector or factor
# To convert them to dates, we need to parse these strings
# This can be done with another appallingly named function, strptime() (fullform: string parse time)
# which returns POSIXlt dates.
# There are as.POSIXct and as.POSIXlt functions too
